name: Matrix Example

on: 
  workflow_call:
    inputs:
      matrix:
        description: 'Matrix:'
        type: string
        required: true

  workflow_dispatch:
    inputs:
      exclude:
        description: 'Exclude triplets:'
        type: string
        default: '[]'
        required: false

jobs:
  Build1:
    strategy:
      matrix: ${{ fromJson(inputs.matrix || '{}' ) }}

    uses: ./.github/workflows/matrix2.yml
    secrets: inherit
    with:
      os: ${{ matrix.os }}
      triplet: ${{ matrix.triplet }}
      config: ${{ matrix.config }}
      host_triplet: ${{ matrix.host_triplet }}
      apt: ${{ matrix.apt }}
      test: ${{ matrix.test }}
