name: Matrix Example

on: 
  push:
  workflow_dispatch:
    inputs:
      exclude:
        description: 'Exclude triplets:'
        type: string
        default: '[]'
        required: false

jobs:
  build:
    strategy:
      matrix:
        triplet: [x86-windows, x64-windows, x86-linux, x64-linux, arm-linux-gnueabi, arm-linux-gnueabihf, aarch64-linux-gnu]
        config: [release, debug]
        exclude: ${{ fromJson(inputs.exclude || '[]') }}
        include:
          - os: windows-latest
            triplet: x86-windows
            host_triplet: x64-windows
            apt: ''
            test: false

          - os: windows-latest
            triplet: x64-windows
            host_triplet: x64-windows
            apt: ''
            test: false

          - os: ubuntu-latest
            triplet: x86-linux
            host_triplet: x64-linux
            apt: gcc-multilib g++-multilib
            test: true

          - os: ubuntu-latest
            triplet: x64-linux
            host_triplet: x64-linux
            apt: ''
            test: true

          - os: ubuntu-latest
            triplet: arm-linux-gnueabi
            host_triplet: x64-linux
            apt: gcc-arm-linux-gnueabi g++-arm-linux-gnueabi
            test: false

          - os: ubuntu-latest
            triplet: arm-linux-gnueabihf
            host_triplet: x64-linux
            apt: gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
            test: false

          - os: ubuntu-latest
            triplet: aarch64-linux-gnu
            host_triplet: x64-linux
            apt: gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
            test: false        

    uses: .github/workflows/matrix2yml
    secrets: inherit
    with:
      os: matrix.os
      triplet: matrix.triplet
      config: matrix.config
      host_triplet: matrix.host_triplet
      apt: matrix.apt
      test: matrix.test
