name: Matrix Example

on: 
  push:
  workflow_dispatch:
    inputs:
      exclude:
        description: 'Exclude triplets:'
        type: string
        default: '[]'
        required: false

jobs:
  Build0:
    uses: ./.github/workflows/matrix1.yml
    secrets: inherit
    with:      
      matrix: >-
        {
          "os": [
            "windows-latest",
            "ubuntu-latest"
          ],
          "triplet": [
            "x86-windows",
            "x64-windows",
            "x86-windows",            
            "x86-linux",
            "x64-linux",
            "arm-linux-gnueabi",
            "arm-linux-gnueabihf",
            "aarch64-linux-gnu"
          ],
          "config": [
            "release",
            "debug"
          ]
        }
