name: Matrix 2 Example

on: 
  workflow_call:
    inputs:
      os:
        description: 'Operating System:'
        type: string
        required: true

      triplet:
        description: 'Triplet:'
        type: string
        required: true

      config:
        description: 'Configuration:'
        type: string
        required: true

      host_triplet:
        description: 'Host Triplet:'
        type: string
        required: true

      apt:
        description: 'Apt:'
        type: string
        default: ''

      test:
        description: 'Test:'
        type: boolean
        default: false

jobs:
  Build2:
    runs-on: ubuntu-latest
    steps:
    - name: Echo2
      run: |
        echo "OS: ${{ inputs.os }}" >> $GITHUB_STEP_SUMMARY
        echo "Triplet: ${{ inputs.triplet }}" >> $GITHUB_STEP_SUMMARY
        echo "Config: ${{ inputs.config }}" >> $GITHUB_STEP_SUMMARY
        echo "Host Triplet: ${{ inputs.host_triplet }}" >> $GITHUB_STEP_SUMMARY
        echo "Apt: ${{ inputs.apt }}" >> $GITHUB_STEP_SUMMARY
        echo "Test: ${{ inputs.test }}" >> $GITHUB_STEP_SUMMARY
