name: Matrix Example

on: 
  push:
  workflow_dispatch:
    inputs:
      exclude:
        description: 'Exclude triplets:'
        type: string
        default: '[]'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        animal: [cat, dog, horse]
        color: [red, green, blue]

        exclude: ${{ fromJson(inputs.exclude || '[]') }}

    steps:
    - name: Echo
      run: |
        echo "Animal: ${{ matrix.animal }}" >> $GITHUB_STEP_SUMMARY
        echo "Color: ${{ matrix.color }}" >> $GITHUB_STEP_SUMMARY
