name: Matrix 2 Example

on: 
  workflow_call:
    inputs:
      triplet:
        description: 'Triplet:'
        type: string
        required: true

      config:
        description: 'Configuration:'
        type: string
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Echo2 
      run: |
        echo "Triplet: ${{ inputs.triplet }}" >> $GITHUB_STEP_SUMMARY
        echo "Config: ${{ inputs.config }}" >> $GITHUB_STEP_SUMMARY

  Test:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - name: Echo2 
      run: |
        echo "Triplet: ${{ inputs.triplet }}" >> $GITHUB_STEP_SUMMARY
        echo "Config: ${{ inputs.config }}" >> $GITHUB_STEP_SUMMARY
